### ISSUE TITLE
(check-type string string) are missing

### ISSUE THREAD

**Issue by sirherrbatka** [rudolfochrist/cl-change-case#5]
(cl-change-case:lower-case nil) => ""
which is not what you most likely want

**Comment by sirherrbatka** [comment]
Some would argue that this library should work on symbols. If that's the case, it does not wok either.

**Comment by sirherrbatka** [comment]
(if (typep object 'fixnum)
                                   (princ-to-string object)
                                   object)
seems shockingly arbitrary

**Comment by rudolfochrist** [comment]
> (cl-change-case:lower-case nil) => "" which is not what you most likely want

Actually this is how it is specified. Now, I'm really curious to hear why "**I**" mostly don't want it like that?
_grabs popcorn..._

**Comment by sirherrbatka** [comment]
Inconsistent with CL. You either ought to treat all symbols as strings (that's 
how string= works for instance) or only treat strings as strings (which is 
more type safe). Having special handling functions (but not in every case) for 
nil being "" is neither plus it does not even follow behavior described in 
docstrings (where it is stated that string, is in fact cl:string).

**Comment by rudolfochrist** [comment]
OK. Adhering to the standard isn't a high priority for me. I make more liberal decisions that suit any problems at hand, but having some type safety isn't a bad thing. 

Since it is a breaking change I add it to the 1.0 milestone.
